### ISSUE TITLE
CSS property names within Media Queries have the wrong text color

### ISSUE THREAD

**Issue by rowild** [dannyconnell/vscode-make-apps-theme#1]
Nice theme! Learned about it in you Youtube courses or a link from there. Thank you!

There are 2 things that would need improvement, though, IMO, if I may say so:

1. On errors in the terminal, the text should be white.
![Screen Shot 2020-11-28 at 00 08 39](https://user-images.githubusercontent.com/213803/100488384-267d9680-310e-11eb-8b9e-f4b7ec8f5812.png)

2. CSS in media queries is colored differently then outside of media queries. The screenshow shows that "color" and "background" are grey within @media, but white outside.
![Screen Shot 2020-11-28 at 00 12 34](https://user-images.githubusercontent.com/213803/100488417-6f354f80-310e-11eb-8f1c-0ca07aaaf0ff.png)
Should stay the same, which is the case, when I deactive the theme:
![Screen Shot 2020-11-28 at 00 13 14](https://user-images.githubusercontent.com/213803/100488435-8bd18780-310e-11eb-980f-89c6eddcf1b4.png)

Would be awesome if you could improve that!!! Thanks!

**Comment by rowild** [comment]
Any news on this one here?

**Comment by dannyconnell** [comment]
@rowild I'll look into the media query issue. I can't recreate the error issue. My errors are just red / white text on the grey background:
<img width="302" alt="Screenshot 2020-12-31 at 14 53 34" src="https://user-images.githubusercontent.com/5763926/103415003-3c9ccd80-4b78-11eb-93c7-4f0757681e47.png">
Can you provide some simple steps that will allow me to see an error like that?
Also, what shell are you using? bash, zsh?

**Comment by dannyconnell** [comment]
@rowild  Fixed the "color of CSS property names within Media Queries" issue and published to Extensions Store. Unable to recreate terminal error color issue. I suspect those terminal colors are being generated by whatever command line tool you're using, so I will close this issue. If I'm wrong & you can provide steps for me to recreate, please open a new issue. Let's keep separate issues separate. Cheers for you help.
